export const getAuthSelector = state => state.auth
export const getNotificationSelector = state => state.notification
export const getThemeSelector = state => state.theme
export const getAdminSelector = state => state.admin
export const getUploadFileSelector = state => state.uploadFile
export const getOrderSelector = state => state.order
export const getMessageSelector = state => state.message
export const getNewsSelector = state => state.news
export const getCommentSelector = state => state.comment
export const getClassRoomSelector = state => state.classRoom
export const getNoteSelector = state => state.note
export const getExerciseSelector = state => state.exercise
export const getExerciseResultSelector = state => state.exerciseResult
export const getLessonSelector = state => state.lesson
export const getHelperSelector = state => state.helper
export const getFeedbackSelector = state => state.feedback
export const getAnalyticsSelector = state => state.analytics
export const getScheduleSelector = state => state.schedule

